server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: vianeo-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5433/vianeo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24 hours

app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:4200,https://localhost:4200}
  admin:
    email: ${ADMIN_EMAIL:admin@vianeo.com}
    password: ${ADMIN_PASSWORD:admin123}

logging:
  level:
    com.vianeo: DEBUG
    org.springframework.security: DEBUG